name: Podspec Dependency Submission
on:
  push:
    branches:
      - main

# The API requires write permission on the repository to submit dependencies
permissions:
  contents: write

jobs:
  podspec-action-detection:
    runs-on: macos-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: Set up CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Run snapshot action
        uses: apptentive/podspec-dependency-submission@v0
        with:
          podspec-path: apptentive-fake-plugin.podspec
