name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
   branches:
      - main
      - 'releases/*'
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM dependencies
        run: npm ci --ignore-scripts

      - name: Set up CocoaPods
        run: |
          sudo gem install cocoapods
          pod repo update

      - name: Build and run tests 
        run: npm rebuild && npm run all

      - name: Verify no uncommitted files
        run: '[ -z "$(git status --porcelain=v1 2>/dev/null)" ]'
        shell: bash
